image: python:3.12
stages:
  - linting
  - test
flake8:
  stage: linting
  image: registry.gitlab.com/mafda/python-linting
  script:
    - flake8 .

run test:
  stage: test
  only:
    - master
  before_script:
    - pip install -r requirements.txt
  script:
    - python -m pytest