stages:
  - test

before_script:
  - python -m venv venv
  - ./venv/Scripts/Activate.ps1
  - pip install -r requirements.txt

run test:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - easysteam/**/*
  script:
    - python -m pytest