stages:
  - test

before_script:
  - python -m venv venv
  - ./venv/Scripts/Activate.ps1
  - pip install -r requirements.txt

run test:
  stage: test
  only:
    refs:
      - master
  rules:
    changes:
      - easysteam/**/*
  script:
    - python -m pytest